@echo off
REM ----------------------------------------------------------------------------
REM Gradle startup script for Windows
REM ----------------------------------------------------------------------------

REM Placeholder. In a real project, gradlew.bat is auto-generated by Gradle.
REM Use `gradle wrapper` to generate this in your repo/environment.